export const TipeOperatorTableLabel = ["No", "Kategori Operasi", "Operasi", "Simbol/Operator", "Deskripsi"];

export const TipeOperatorTableIsian = [
    {
        Nomor: "1",
        Kategori: "Aritmatika",
        Operasi: "Penjumlahan",
        Operator: "+",
        Deskripsi: "Menjumlahkan dua angka.",
    },
    {
        Nomor: "2",
        Kategori: "Aritmatika",
        Operasi: "Pengurangan",
        Operator: "	-",
        Deskripsi: "Mengurangi satu angka dari angka lain.",
    },
    {
        Nomor: "3",
        Kategori: "Aritmatika",
        Operasi: "Perkalian",
        Operator: "	*",
        Deskripsi: "Mengalikan dua angka.",
    },
    {
        Nomor: "4",
        Kategori: "Aritmatika",
        Operasi: "Pembagian",
        Operator: "	/",
        Deskripsi: "Membagi satu angka dengan angka lain.",
    },
    {
        Nomor: "5",
        Kategori: "Aritmatika",
        Operasi: "Modulus (Sisa Bagi)",
        Operator: '"%"',
        Deskripsi: "Menghasilkan sisa pembagian dua angka.",
    },
    {
        Nomor: "6",
        Kategori: "Perbandingan",
        Operasi: "Sama Dengan",
        Operator: "	==",
        Deskripsi: "Memeriksa apakah dua nilai sama.",
    },
    {
        Nomor: "7",
        Kategori: "Perbandingan",
        Operasi: "Tidak Sama Dengan",
        Operator: "!=",
        Deskripsi: "Memeriksa apakah dua nilai berbeda.",
    },
    {
        Nomor: "8",
        Kategori: "Perbandingan",
        Operasi: "Lebih Besar",
        Operator: ">",
        Deskripsi: "Memeriksa apakah nilai pertama lebih besar dari nilai kedua.",
    },
    {
        Nomor: "9",
        Kategori: "Perbandingan",
        Operasi: "Lebih Kecil",
        Operator: "	<",
        Deskripsi: "Memeriksa apakah nilai pertama lebih kecil dari nilai kedua.",
    },
    {
        Nomor: "10",
        Kategori: "Perbandingan",
        Operasi: "Lebih Besar atau Sama",
        Operator: ">=",
        Deskripsi: "Memeriksa apakah nilai pertama lebih besar atau sama dengan nilai kedua.",
    },
    {
        Nomor: "11",
        Kategori: "Perbandingan",
        Operasi: "Lebih Kecil atau Sama",
        Operator: "<=",
        Deskripsi: "Memeriksa apakah nilai pertama lebih kecil atau sama dengan nilai kedua.",
    },
    {
        Nomor: "12",
        Kategori: "Logika",
        Operasi: "AND (Dan)",
        Operator: "&&",
        Deskripsi: "Menghasilkan true jika kedua kondisi bernilai true.",
    },
    {
        Nomor: "13",
        Kategori: "Logika",
        Operasi: "OR (Atau)",
        Operator: "||",
        Deskripsi: "Menghasilkan true jika salah satu dari kondisi bernilai true.",
    },
    {
        Nomor: "14",
        Kategori: "Logika",
        Operasi: "NOT (Tidak)",
        Operator: "!",
        Deskripsi: "Membalikkan nilai logika (dari true menjadi false atau sebaliknya).",
    },
];
